// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SqlDBContext))]
    partial class SqlDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Domain.Models.AppConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppConfig");
                });

            modelBuilder.Entity("Domain.Models.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("BonusFirstElementId")
                        .HasColumnType("integer");

                    b.Property<int?>("BonusSecondElementId")
                        .HasColumnType("integer");

                    b.Property<int?>("BonusThirdElementId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CalculationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("InvoicePrice")
                        .HasColumnType("double precision");

                    b.Property<double?>("InvoiceSum")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MainFirstElementId")
                        .HasColumnType("integer");

                    b.Property<int?>("MainSecondElementId")
                        .HasColumnType("integer");

                    b.Property<int?>("MainThirdElementId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("PdId")
                        .HasColumnType("integer");

                    b.Property<double?>("Price")
                        .HasColumnType("double precision");

                    b.Property<int?>("PtId")
                        .HasColumnType("integer");

                    b.Property<double?>("ResultPercent")
                        .HasColumnType("double precision");

                    b.Property<int?>("RhId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryFirstElementId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondarySecondElementId")
                        .HasColumnType("integer");

                    b.Property<int?>("SecondaryThirdElementId")
                        .HasColumnType("integer");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BonusFirstElementId");

                    b.HasIndex("BonusSecondElementId");

                    b.HasIndex("BonusThirdElementId");

                    b.HasIndex("MainFirstElementId");

                    b.HasIndex("MainSecondElementId");

                    b.HasIndex("MainThirdElementId");

                    b.HasIndex("PdId");

                    b.HasIndex("PtId");

                    b.HasIndex("RhId");

                    b.HasIndex("SecondaryFirstElementId");

                    b.HasIndex("SecondarySecondElementId");

                    b.HasIndex("SecondaryThirdElementId");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("Domain.Models.CommonCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SortNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Name", "Code")
                        .IsUnique();

                    b.ToTable("CommonCodes");
                });

            modelBuilder.Entity("Domain.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Phone")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("SecondName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Domain.Models.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CommonCodeNameId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FixId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<double?>("NetWeight")
                        .HasColumnType("double precision");

                    b.Property<double?>("Percent")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<double?>("Result")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CommonCodeNameId");

                    b.HasIndex("FixId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("Domain.Models.Fix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FixOrderId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("ShipmentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FixOrderId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("Fixs");
                });

            modelBuilder.Entity("Domain.Models.FixOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AdditionalFieldName")
                        .HasColumnType("text");

                    b.Property<decimal?>("AdditionalFieldValue")
                        .HasColumnType("numeric");

                    b.Property<int?>("CalculationId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommonCodeCurrencyId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommonCodeStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("CommonCodeWeightUomId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CurrencyRates")
                        .HasColumnType("numeric");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("IncurredCosts")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<double?>("NetWeight")
                        .HasColumnType("double precision");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ShipmentId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CalculationId");

                    b.HasIndex("CommonCodeCurrencyId");

                    b.HasIndex("CommonCodeStatusId");

                    b.HasIndex("CommonCodeWeightUomId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.HasIndex("ShipmentId");

                    b.ToTable("FixOrders");
                });

            modelBuilder.Entity("Domain.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Addr1")
                        .HasColumnType("text");

                    b.Property<string>("Addr2")
                        .HasColumnType("text");

                    b.Property<string>("Addr3")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("IsoCountryCode")
                        .HasColumnType("text");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Zip")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name", "Country")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Domain.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CommonCodeStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DateStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CommonCodeStatusId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Models.Calculation", b =>
                {
                    b.HasOne("Domain.Models.Element", "BonusFirstElement")
                        .WithMany()
                        .HasForeignKey("BonusFirstElementId");

                    b.HasOne("Domain.Models.Element", "BonusSecondElement")
                        .WithMany()
                        .HasForeignKey("BonusSecondElementId");

                    b.HasOne("Domain.Models.Element", "BonusThirdElement")
                        .WithMany()
                        .HasForeignKey("BonusThirdElementId");

                    b.HasOne("Domain.Models.Element", "MainFirstElement")
                        .WithMany()
                        .HasForeignKey("MainFirstElementId");

                    b.HasOne("Domain.Models.Element", "MainSecondElement")
                        .WithMany()
                        .HasForeignKey("MainSecondElementId");

                    b.HasOne("Domain.Models.Element", "MainThirdElement")
                        .WithMany()
                        .HasForeignKey("MainThirdElementId");

                    b.HasOne("Domain.Models.Element", "Pd")
                        .WithMany()
                        .HasForeignKey("PdId");

                    b.HasOne("Domain.Models.Element", "Pt")
                        .WithMany()
                        .HasForeignKey("PtId");

                    b.HasOne("Domain.Models.Element", "Rh")
                        .WithMany()
                        .HasForeignKey("RhId");

                    b.HasOne("Domain.Models.Element", "SecondaryFirstElement")
                        .WithMany()
                        .HasForeignKey("SecondaryFirstElementId");

                    b.HasOne("Domain.Models.Element", "SecondarySecondElement")
                        .WithMany()
                        .HasForeignKey("SecondarySecondElementId");

                    b.HasOne("Domain.Models.Element", "SecondaryThirdElement")
                        .WithMany()
                        .HasForeignKey("SecondaryThirdElementId");

                    b.Navigation("BonusFirstElement");

                    b.Navigation("BonusSecondElement");

                    b.Navigation("BonusThirdElement");

                    b.Navigation("MainFirstElement");

                    b.Navigation("MainSecondElement");

                    b.Navigation("MainThirdElement");

                    b.Navigation("Pd");

                    b.Navigation("Pt");

                    b.Navigation("Rh");

                    b.Navigation("SecondaryFirstElement");

                    b.Navigation("SecondarySecondElement");

                    b.Navigation("SecondaryThirdElement");
                });

            modelBuilder.Entity("Domain.Models.CommonCode", b =>
                {
                    b.HasOne("Domain.Models.CommonCode", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Domain.Models.Customer", b =>
                {
                    b.HasOne("Domain.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("Domain.Models.Element", b =>
                {
                    b.HasOne("Domain.Models.CommonCode", "CommonCodeName")
                        .WithMany()
                        .HasForeignKey("CommonCodeNameId");

                    b.HasOne("Domain.Models.Fix", "Fix")
                        .WithMany("Elements")
                        .HasForeignKey("FixId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CommonCodeName");

                    b.Navigation("Fix");
                });

            modelBuilder.Entity("Domain.Models.Fix", b =>
                {
                    b.HasOne("Domain.Models.FixOrder", "FixOrder")
                        .WithMany("Fixs")
                        .HasForeignKey("FixOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Shipment", null)
                        .WithMany("Fixs")
                        .HasForeignKey("ShipmentId");

                    b.Navigation("FixOrder");
                });

            modelBuilder.Entity("Domain.Models.FixOrder", b =>
                {
                    b.HasOne("Domain.Models.Calculation", "Calculation")
                        .WithMany()
                        .HasForeignKey("CalculationId");

                    b.HasOne("Domain.Models.CommonCode", "CommonCodeCurrency")
                        .WithMany()
                        .HasForeignKey("CommonCodeCurrencyId");

                    b.HasOne("Domain.Models.CommonCode", "CommonCodeStatus")
                        .WithMany()
                        .HasForeignKey("CommonCodeStatusId");

                    b.HasOne("Domain.Models.CommonCode", "CommonCodeWeightUom")
                        .WithMany()
                        .HasForeignKey("CommonCodeWeightUomId");

                    b.HasOne("Domain.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Domain.Models.Shipment", "Shipment")
                        .WithMany()
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calculation");

                    b.Navigation("CommonCodeCurrency");

                    b.Navigation("CommonCodeStatus");

                    b.Navigation("CommonCodeWeightUom");

                    b.Navigation("Customer");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("Domain.Models.Shipment", b =>
                {
                    b.HasOne("Domain.Models.CommonCode", "CommonCodeStatus")
                        .WithMany()
                        .HasForeignKey("CommonCodeStatusId");

                    b.Navigation("CommonCodeStatus");
                });

            modelBuilder.Entity("Domain.Models.Fix", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("Domain.Models.FixOrder", b =>
                {
                    b.Navigation("Fixs");
                });

            modelBuilder.Entity("Domain.Models.Shipment", b =>
                {
                    b.Navigation("Fixs");
                });
#pragma warning restore 612, 618
        }
    }
}
